---
title: "MHRiseCommunity"
author: "Tristano Munini"
date: "29/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting Started with TwitterAPI
Following [this](https://www.earthdatascience.org/courses/earth-analytics/get-data-using-apis/use-twitter-api-r/) tutorial
```{r}
library(rtweet)
library(ggplot2)
library(dplyr)
library(tidytext)
```


```{r}
json_keys = jsonlite::read_json("keys/keys.json")

appname = json_keys$appname
key     = json_keys$key
secret  = json_keys$secret
access_token  = json_keys$access_token
access_secret = json_keys$access_secret

# create token named "twitter_token"
twitter_token = create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  access_token = access_token,
  access_secret = access_secret
)

remove(json_keys)
remove(appname)
remove(key)
remove(secret)
remove(access_token)
remove(access_secret)
```

## Data collection
```{r}
DOWNLOAD_DATA = TRUE
DOWNLOAD_DIR = "./CSVs"
```

```{r}
get_timestamp = function (){ format(Sys.time(), "%Y%m%d_%H%M%S") }

#download_followers = function (account_name, n=-1, retryonratelimit = FALSE, download_dir=DOWNLOAD_DIR) {
#  
#}

```





```{r}
if (DOWNLOAD_DATA) {
  account_name = "monsterhunter"
  mh_followers = get_followers(account_name, n=500000, retryonratelimit = TRUE)
  file_name = paste(account_name, get_timestamp(), sep = "__")
  file_path = paste(DOWNLOAD_DIR, file_name, sep = "/")
  write_as_csv(mh_followers, file_path)
} else {
  #mh_followers = read_twitter_csv(paste(download_dir, "mh_followers.csv", sep = "/" ))
  show("TODO")
}
mh_followers
```


```{r}
if (DOWNLOAD_DATA) {
  account_name = "arekkz"
  arekkz_followers = get_followers(account_name, n=500000, retryonratelimit = TRUE)
  file_name = paste(account_name, get_timestamp(), sep = "__")
  file_path = paste(DOWNLOAD_DIR, file_name, sep = "/")
  write_as_csv(arekkz_followers, file_path)
} else {
  #arekkz = read_twitter_csv(paste(download_dir, "mh_followers.csv", sep = "/" ))
  show("TODO")
}
arekkz_followers
```


```{r}
if (DOWNLOAD_DATA) {
  account_name = "aevanko"
  aevanko_followers = get_followers(account_name, n=500000, retryonratelimit = TRUE)
  file_name = paste(account_name, get_timestamp(), sep = "__")
  file_path = paste(DOWNLOAD_DIR, file_name, sep = "/")
  write_as_csv(aevanko_followers, file_path)
} else {
  #aevanko = read_twitter_csv(paste(download_dir, "mh_followers.csv", sep = "/" ))
  show("TODO")
}
aevanko_followers
```





# Alternativa
per ogni follower di mh prendere 100 follows casuali e vedere se emergono gli hub previsti (arekkz, aevanko, socks...)













































